favicon: null
name: Aquaponica
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9998955391347408
  brandStrength: 0.3199049597606063
  rhythmicContrast: 0.3488220693543553
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.998281913343817
typography_spectrum: 0.6980147114954889
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.7998805
analytics:
  twitter: null
  google: null
  facebook: null
